1)Load the Iris dataset and explore its structure using functions like df.head().

2)Extract features (X) and the target variable (y) from the dataset.

3)Encode the target variable (y) .

4)Normalize the feature set (X).

5)Split the dataset into training and testing sets .

6)Implement and train a LinearRegression model, then use it to predict on the test data.

7)Implement and train a LogisticRegression model, then use it to predict on the test data.

8)Implement and train an SGDClassifier with logistic loss, then use it to predict on the test data.

9)Evaluate the models’ performance by calculating accuracy or other metrics.

10)Save and compare the actual and predicted labels from all models in a DataFrame.

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression, SGDClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder

1. Load the Iris Dataset

In [3]:
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target
print(df)
df.head()


     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

2. Select Features and Target

In [5]:
x=df[iris.feature_names]
y=df['target']


     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]
----
0      0
1      0
2      0
3      0

3. Encode the Target Variable

In [6]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

print(y_encoded)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


4. Normalize Features

In [10]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

print(x_scaled)


[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

5. Split the Dataset

In [35]:
X_train, X_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.3, random_state=8)

6. Implement Linear Regression

In [36]:
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
y_pred_linear = np.round(linear_model.predict(X_test)).astype(int)

7. Implement Logistic Regression

In [37]:
logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)
y_pred_logistic = logistic_model.predict(X_test)

8. Implement SGD (Stochastic Gradient Descent)

In [38]:
sgd_model = SGDClassifier(loss='log_loss', random_state=8)
sgd_model.fit(X_train, y_train)
y_pred_sgd = sgd_model.predict(X_test)

9. Evaluate the Models

In [39]:
from sklearn.metrics import accuracy_score

print("Linear Regression Accuracy:", accuracy_score(y_test, y_pred_linear))
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_logistic))
print("SGD Accuracy:", accuracy_score(y_test, y_pred_sgd))

Linear Regression Accuracy: 0.9333333333333333
Logistic Regression Accuracy: 0.8888888888888888
SGD Accuracy: 0.8444444444444444


10. Save Predictions

In [40]:
submission = pd.DataFrame({
    'Actual': y_test,
    'Predicted_Linear': y_pred_linear,
    'Predicted_Logistic': y_pred_logistic,
    'Predicted_SGD': y_pred_sgd
})
print(submission)

    Actual  Predicted_Linear  Predicted_Logistic  Predicted_SGD
0        0                 0                   0              0
1        0                 0                   0              0
2        0                 0                   0              0
3        2                 2                   2              2
4        1                 1                   1              1
5        0                 0                   0              0
6        0                 0                   0              0
7        2                 2                   2              2
8        2                 2                   2              2
9        1                 1                   1              1
10       1                 1                   1              2
11       0                 0                   0              0
12       2                 2                   1              1
13       1                 1                   1              1
14       2                 1            